
import java.awt.HeadlessException;
import java.io.IOException;
import javax.swing.JOptionPane;

public class EditProfile extends javax.swing.JFrame implements Buttons{

    private final static String filePath = "StudentRecord.txt";
    static String editRecord = "";
    private final int NUMBER_OF_ROOMS = 20;

    
    @Override
    public void reset() {
        firstNameField.setText("");
        middleNameField.setText("");
        lastNameField.setText("");
        fatherNameField.setText("");
        phoneNoField.setText("");
        emailField.setText("");
        studentIdField.setText("");
        genderRadiobtnGroup.clearSelection();
        countryCbox.setSelectedIndex(0);
        roomCbox.setSelectedIndex(3);
        ageField.setText("");
        addressTextarea.setText("");
        //For Room
        roomCbox.removeAllItems();
        for(int i = 1; i <= NUMBER_OF_ROOMS; i++){
            roomCbox.addItem("ROOM " + i);
        }
        runned = 0;
    }

    @Override
    public void cancel() {
    }

    @Override
    public void back() {
        dispose();
        Option obj = new Option();
        obj.setVisible(true);
    }

    @Override
    public void search() {
        //Checking if Student Id entered is correct
        String input = searchField.getText().trim();
        boolean valid = Validation.studentIdIsValid(input);
        
        if (!valid) {
            JOptionPane.showMessageDialog(null, "Error\nField is Empty OR\nInvalid Student Id\ne.g. cs201076");
        } else {
            String line = Record.searchRecord(searchField.getText().trim());
            if (!line.equals("")) {  //Checks whether record was found before putting on Table
                reset();
                        
                editRecord = line;
                String data[] = line.split("\\|");
                
                studentIdField.setText(data[0]);
                firstNameField.setText(data[1]);
                middleNameField.setText(data[2]);
                lastNameField.setText(data[3]);
                fatherNameField.setText(data[4]);
                phoneNoField.setText(data[5]);
                emailField.setText(data[6]);
                if (data[7].equalsIgnoreCase("Male"))
                    maleRadioBtn.setSelected(true);
                else
                    femaleRadioBtn.setSelected(true);
                ageField.setText(data[8]);
                countryCbox.setSelectedItem(data[9]);
                roomCbox.setSelectedItem(data[10]);
                oldRoom = data[10]; //Used check if room picked is uniqe
                addressTextarea.setText(data[11]);
                
                //Used in Editing data in updateBtn method
                oldRoom = data[10];

            } else {
                JOptionPane.showMessageDialog(null, "Record Not Found.");
            }
        }
    }

    @Override
    public void loadAll() {
    }
    
    
    /**
     * Creates new form EditProfile
     */
    public EditProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderRadiobtnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        firstNamLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        middleNameField = new javax.swing.JTextField();
        middleNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        fatherNameField = new javax.swing.JTextField();
        fatherNameLabel = new javax.swing.JLabel();
        phoneNoField = new javax.swing.JTextField();
        phoneNoLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        studentIdField = new javax.swing.JTextField();
        studentIdLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        maleRadioBtn = new javax.swing.JRadioButton();
        femaleRadioBtn = new javax.swing.JRadioButton();
        ageField = new javax.swing.JTextField();
        roomLabel = new javax.swing.JLabel();
        ageLabel1 = new javax.swing.JLabel();
        roomCbox = new javax.swing.JComboBox<>();
        ageLabel2 = new javax.swing.JLabel();
        countryCbox = new javax.swing.JComboBox<>();
        addresLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextarea = new javax.swing.JTextArea();
        updateBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Profile");

        jPanel1.setBackground(new java.awt.Color(0, 24, 69));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\HMS Project\\SelectOption\\icons\\edit (1).png")); // NOI18N
        jLabel1.setText(" Edit Profile");

        searchBtn.setBackground(new java.awt.Color(255, 255, 255));
        searchBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        searchBtn.setIcon(new javax.swing.ImageIcon("C:\\HMS Project\\SelectOption\\icons\\search.png")); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setBorder(null);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        firstNamLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        firstNamLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNamLabel.setText("First Name :");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Student ID : e.g. cs201161");

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        middleNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleNameFieldActionPerformed(evt);
            }
        });

        middleNameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        middleNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        middleNameLabel.setText("Middle Name :");

        lastNameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setText("Last Name :");

        fatherNameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fatherNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        fatherNameLabel.setText("Father Name :");

        phoneNoLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        phoneNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneNoLabel.setText("Phone No :");

        emailLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email :");

        studentIdField.setEditable(false);
        studentIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdFieldActionPerformed(evt);
            }
        });

        studentIdLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        studentIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentIdLabel.setText("Student ID :");

        genderLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText("Gender :");

        genderRadiobtnGroup.add(maleRadioBtn);
        maleRadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        maleRadioBtn.setText("Male");
        maleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioBtnActionPerformed(evt);
            }
        });

        genderRadiobtnGroup.add(femaleRadioBtn);
        femaleRadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        femaleRadioBtn.setText("Female");

        ageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFieldActionPerformed(evt);
            }
        });

        roomLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        roomLabel.setForeground(new java.awt.Color(255, 255, 255));
        roomLabel.setText("Room :");

        ageLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ageLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ageLabel1.setText("Age:");

        roomCbox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        roomCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ROOM 1", "ROOM 2", "ROOM 3", "ROOM 4", "ROOM 5", "ROOM 6", "ROOM 7", "ROOM 8", "ROOM 9", "ROOM 10", "ROOM 11", "ROOM 12", "ROOM 13", "ROOM 14", "ROOM 15", "ROOM 16", "ROOM 17", "ROOM 18", "ROOM 19", "ROOM 20" }));
        roomCbox.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                roomCboxMouseMoved(evt);
            }
        });
        roomCbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomCboxActionPerformed(evt);
            }
        });

        ageLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ageLabel2.setForeground(new java.awt.Color(255, 255, 255));
        ageLabel2.setText("Country :");

        countryCbox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        countryCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAKISTAN", "BANGLADESH", "AFGHANISTAN", "NEPAL" }));
        countryCbox.setToolTipText("");

        addresLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addresLabel.setForeground(new java.awt.Color(255, 255, 255));
        addresLabel.setText("Address :");

        addressTextarea.setColumns(20);
        addressTextarea.setRows(5);
        jScrollPane1.setViewportView(addressTextarea);

        updateBtn.setBackground(new java.awt.Color(255, 255, 255));
        updateBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        updateBtn.setIcon(new javax.swing.ImageIcon("C:\\HMS Project\\SelectOption\\icons\\update.png")); // NOI18N
        updateBtn.setText("Update");
        updateBtn.setBorder(null);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        resetBtn.setBackground(new java.awt.Color(255, 255, 255));
        resetBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        resetBtn.setIcon(new javax.swing.ImageIcon("C:\\HMS Project\\SelectOption\\icons\\resert.png")); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.setBorder(null);
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("   HMS 2021   Version 1.0                                                                                                                                                                        Need Help ?");

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon("C:\\HMS Project\\SelectOption\\icons\\back.png")); // NOI18N
        backBtn.setText("Back");
        backBtn.setBorder(null);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneNoLabel)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(searchField)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(firstNamLabel)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(firstNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                                            .addComponent(middleNameField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lastNameField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fatherNameField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(phoneNoField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailField, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(middleNameLabel)
                                        .addComponent(lastNameLabel)
                                        .addComponent(fatherNameLabel)
                                        .addComponent(emailLabel))
                                    .addGap(118, 118, 118)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(countryCbox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ageLabel2)
                                                .addComponent(addresLabel))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(roomLabel)
                                                .addComponent(roomCbox, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(studentIdLabel)
                                                .addComponent(genderLabel)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(maleRadioBtn)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(femaleRadioBtn))
                                                .addComponent(ageLabel1)
                                                .addComponent(studentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(ageField)))))))
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchField, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addComponent(firstNamLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(studentIdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderLabel)
                    .addComponent(middleNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(middleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maleRadioBtn)
                    .addComponent(femaleRadioBtn))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLabel)
                            .addComponent(ageLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fatherNameLabel)
                            .addComponent(roomLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fatherNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(countryCbox)
                            .addComponent(roomCbox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneNoLabel)
                            .addComponent(addresLabel)))
                    .addComponent(ageLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(phoneNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFieldActionPerformed

    private void maleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioBtnActionPerformed

    private void studentIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIdFieldActionPerformed

    private void middleNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameFieldActionPerformed

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed
    
    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        searchField.setText("");
        oldRoom = "";
        reset();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        back();
    }//GEN-LAST:event_backBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        search();
    }//GEN-LAST:event_searchBtnActionPerformed
    static String oldRoom;
    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        
        
        String firstName = firstNameField.getText().trim();
        String middleName = middleNameField.getText().trim();
        String lastName = lastNameField.getText().trim();
        String fatherName = fatherNameField.getText().trim();
        String phoneNo = phoneNoField.getText().trim();
        String email = emailField.getText().trim();
        String studentId = studentIdField.getText().trim();
        String gender;
        if (maleRadioBtn.isSelected()) gender = "Male";
        else gender = "Female";
        String age = ageField.getText().trim();
        String country = countryCbox.getSelectedItem().toString();
        String newRoom = roomCbox.getSelectedItem().toString();
        newRoom = roomCbox.getSelectedItem().toString();
        String address = addressTextarea.getText().replaceAll("\n", " ").trim();
        
        
        //TO CHECK IF ANY INPUT IS BLANK OR NULL
        if (Validation.isBlank(firstName)
                || Validation.isBlank(middleName)
                || Validation.isBlank(lastName)
                || Validation.isBlank(fatherName)
                || Validation.isBlank(phoneNo)
                || Validation.isBlank(email)
                || Validation.isBlank(studentId)
                || Validation.isBlank(age)
                || Validation.isBlank(address)
                || !(maleRadioBtn.isSelected() || femaleRadioBtn.isSelected())) {
            JOptionPane.showMessageDialog(null, "Can't Leave Any Box Empty.");

        //TO CHECK IF FORMAT IS WRONG OR NOT VALID
        } else if (!Validation.nameIsValid(firstName)) {
            JOptionPane.showMessageDialog(null, "Invalid First Name.");
        } else if (!Validation.nameIsValid(middleName)) {
            JOptionPane.showMessageDialog(null, "Invalid Middle Name.");
        } else if (!Validation.nameIsValid(lastName)) {
            JOptionPane.showMessageDialog(null, "Invalid Last Name.");
        } else if (!Validation.fatherNameIsValid(fatherName)) {
            JOptionPane.showMessageDialog(null, "Invalid Father Name.");
        } else if (!Validation.phoneNoIsValid(phoneNo)) {
            JOptionPane.showMessageDialog(null, "Invalid Phone No.");
        } else if (!Validation.emailIsValid(email)) {
            JOptionPane.showMessageDialog(null, "Invalid Email.");
        } else if (!Validation.studentIdIsValid(studentId)){
            JOptionPane.showMessageDialog(null, "Invalid Student ID/Format\ne.g. : cs201062");
        } else if (!Validation.ageIsValid(age)) {
            JOptionPane.showMessageDialog(null, "Invalid Age.");
        }else if (!newRoom.equalsIgnoreCase(oldRoom) && Record.recordExist(newRoom)) {
            JOptionPane.showMessageDialog(null, "Room is Taken.");
        } else if (!Validation.addressIsValid(address)){
            JOptionPane.showMessageDialog(null, "Invalid Address\nDon't Use '|'.");
        }
        else{
            
            try {
                Student std = new Student(firstName, middleName, lastName, fatherName, phoneNo, email, studentId, gender, age, country, newRoom, address);
                Record.saveRecord(std, studentId);
                reset();
                JOptionPane.showMessageDialog(null, "Record have been Updated.");
            } catch (HeadlessException | IOException ex) {
                JOptionPane.showMessageDialog(null, "Error Occurd While Editing the File.");
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed
    private static int runned = 0;
    private void roomCboxMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomCboxMouseMoved
       final int count = roomCbox.getItemCount();
        
        if(!studentIdField.getText().equals("") && runned <= count) {
            for(int i = 0; i < roomCbox.getItemCount(); i++){
                if(Record.recordExist(roomCbox.getItemAt(i)) && !roomCbox.getItemAt(i).equals(oldRoom))
                    roomCbox.removeItemAt(i);
            }
            runned++;
        }
    }//GEN-LAST:event_roomCboxMouseMoved

    private void roomCboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomCboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomCboxActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EditProfile().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresLabel;
    private javax.swing.JTextArea addressTextarea;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel1;
    private javax.swing.JLabel ageLabel2;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> countryCbox;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField fatherNameField;
    private javax.swing.JLabel fatherNameLabel;
    private javax.swing.JRadioButton femaleRadioBtn;
    private javax.swing.JLabel firstNamLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel genderLabel;
    private javax.swing.ButtonGroup genderRadiobtnGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JRadioButton maleRadioBtn;
    private javax.swing.JTextField middleNameField;
    private javax.swing.JLabel middleNameLabel;
    private javax.swing.JTextField phoneNoField;
    private javax.swing.JLabel phoneNoLabel;
    private javax.swing.JButton resetBtn;
    private javax.swing.JComboBox<String> roomCbox;
    private javax.swing.JLabel roomLabel;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextField studentIdField;
    private javax.swing.JLabel studentIdLabel;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
